variables:
  GRUB_VERSION: '2.04'
  DOCKER_REPOSITORY: mendersoftware/mender-convert-integration-scripts
  S3_BUCKET_NAME: mender

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'

stages:
  - test
  - build
  - publish

build:uboot:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - IMAGE_NAME=$DOCKER_REPOSITORY:pr ./docker-create-integration-binaries
  artifacts:
    expire_in: 2w
    paths:
      - output/*

build:grub-efi:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - apk --update --no-cache add libc6-compat
  script:
    - (cd grub-efi && GRUB_VERSION=$GRUB_VERSION ./docker-create-grub-efi-binaries)
  artifacts:
    expire_in: 2w
    paths:
      - grub-efi/output/*

publish:s3:
  stage: publish
  image: debian:buster
  dependencies:
    - build:uboot
    - build:grub-efi
  before_script:
    - apt update && apt install -yyq awscli
  script:
    - ./prepare-output-folder-for-upload
    - aws s3 cp --recursive --acl public-read output/upload/ s3://$S3_BUCKET_NAME/mender-convert/
  only:
    - /^(master|[0-9]+\.[0-9]+\.x)$/
